version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: cimg/android:2021.10.2-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Generate google-services.json
          command: echo $GOOGLE_SERVICES | base64 --decode > app/google-services.json
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Assemble
          command: ./gradlew assemble
      - run:
          name: Unit Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: core/build/reports
          destination: core/reports
      - store_artifacts:
          path: solana/build/reports
          destination: solana/reports
      - store_test_results:
          path: core/build/test-results
      - store_test_results:
          path: solana/build/test-results

workflows:
  version: 2
  workflow:
    jobs:
      - build
